// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeU9btCpCyOiyZio0mwbT6aFNJSCZ-1tI',
    appId: '1:834823385148:web:af3dbd6b7e8df58d66d339',
    messagingSenderId: '834823385148',
    projectId: 'firebase-checking123',
    authDomain: 'fir-checking123.firebaseapp.com',
    storageBucket: 'firebase-checking123.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKLJ8tAQAny3rPuI7NCqudItlhlc86Cx8',
    appId: '1:834823385148:android:a2cd52eea398240f66d339',
    messagingSenderId: '834823385148',
    projectId: 'firebase-checking123',
    storageBucket: 'firebase-checking123.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkVewIo6kH-iOCJye5I7UnAxBI9sXTF-c',
    appId: '1:834823385148:ios:aa3ae0e5c02a425866d339',
    messagingSenderId: '834823385148',
    projectId: 'firebase-checking123',
    storageBucket: 'firebase-checking123.appspot.com',
    iosClientId:
        '834823385148-egt2quvrc5lvjk45n45johvgh5n6iv4d.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningdart',
  );
}
